second_commit
maksim-chubura/Sprint_4 pull request #1
Opened 2023-04-23 11:15 UTC by maksim-chubura

Финальный проект 4 спринта - Чубура Максим

2023-04-24 15:37 UTC, alstafeev requested changes

2023-04-24 15:37 UTC, alstafeev commented on src/test/java/HomePageTest.java
> +    public void checkTestSecondQuestions() {
Надо проверять все вопросы и ответы, а не только первые два

2023-04-25 05:19 UTC, maksim-chubura commented on src/test/java/HomePageTest.java
> +    public void checkTestSecondQuestions() {
Подскажите, срок сдачи доработки и достаточно будет по такому же принципу дописать проверки остальных вопросов?

2023-04-26 07:52 UTC, maksim-chubura commented
Работа принята

2023-04-26 07:54 UTC, merged